export const booksList = [
  { Id: 1, BookNo: "B001", Owner: "John Smith", Status: true, Price: 15.99 },
  { Id: 2, BookNo: "B002", Owner: "Emily Johnson", Status: false, Price: 8.5 },
  { Id: 3, BookNo: "B003", Owner: "Michael Brown", Status: true, Price: 12.75 },
  { Id: 4, BookNo: "B004", Owner: "Sarah Davis", Status: false, Price: 20.0 },
  { Id: 5, BookNo: "B005", Owner: "David Wilson", Status: true, Price: 7.99 },
  {
    Id: 6,
    BookNo: "B006",
    Owner: "Jessica Miller",
    Status: false,
    Price: 13.49,
  },
  {
    Id: 7,
    BookNo: "B007",
    Owner: "Daniel Anderson",
    Status: true,
    Price: 6.25,
  },
  { Id: 8, BookNo: "B008", Owner: "Laura Thomas", Status: false, Price: 9.99 },
  { Id: 9, BookNo: "B009", Owner: "Kevin Martinez", Status: true, Price: 5.5 },
  {
    Id: 10,
    BookNo: "B010",
    Owner: "Jennifer Taylor",
    Status: false,
    Price: 11.99,
  },
  {
    Id: 11,
    BookNo: "B011",
    Owner: "William Harris",
    Status: true,
    Price: 14.5,
  },
  {
    Id: 12,
    BookNo: "B012",
    Owner: "Elizabeth Clark",
    Status: false,
    Price: 10.75,
  },
  {
    Id: 13,
    BookNo: "B013",
    Owner: "Christopher Lewis",
    Status: true,
    Price: 7.25,
  },
  {
    Id: 14,
    BookNo: "B014",
    Owner: "Patricia Walker",
    Status: false,
    Price: 18.99,
  },
  { Id: 15, BookNo: "B015", Owner: "Matthew Hall", Status: true, Price: 9.49 },
  { Id: 16, BookNo: "B016", Owner: "Ashley Young", Status: false, Price: 16.0 },
  { Id: 17, BookNo: "B017", Owner: "Joshua King", Status: true, Price: 5.75 },
  {
    Id: 18,
    BookNo: "B018",
    Owner: "Amanda Wright",
    Status: false,
    Price: 13.99,
  },
  { Id: 19, BookNo: "B019", Owner: "Andrew Scott", Status: true, Price: 8.99 },
  { Id: 20, BookNo: "B020", Owner: "Megan Green", Status: false, Price: 17.25 },
];

export const booksListAdmin = [
  {
    author: "John Grisham",
    owner: "John Smith",
    category: "Fiction",
    status: true,
    bookName: "The Firm",
  },
  {
    author: "J.K. Rowling",
    owner: "Emily Johnson",
    category: "Fantasy",
    status: false,
    bookName: "Harry Potter and the Sorcerer's Stone",
  },
  {
    author: "Stephen King",
    owner: "Michael Brown",
    category: "Horror",
    status: true,
    bookName: "The Shining",
  },
  {
    author: "Agatha Christie",
    owner: "Sarah Davis",
    category: "Mystery",
    status: false,
    bookName: "Murder on the Orient Express",
  },
  {
    author: "James Patterson",
    owner: "David Wilson",
    category: "Thriller",
    status: true,
    bookName: "Along Came a Spider",
  },
  {
    author: "George Orwell",
    owner: "Jessica Miller",
    category: "Dystopian",
    status: false,
    bookName: "1984",
  },
  {
    author: "Jane Austen",
    owner: "Daniel Anderson",
    category: "Romance",
    status: true,
    bookName: "Pride and Prejudice",
  },
  {
    author: "Mark Twain",
    owner: "Laura Thomas",
    category: "Classic",
    status: false,
    bookName: "The Adventures of Tom Sawyer",
  },
  {
    author: "Ernest Hemingway",
    owner: "Kevin Martinez",
    category: "Literature",
    status: true,
    bookName: "The Old Man and the Sea",
  },
  {
    author: "F. Scott Fitzgerald",
    owner: "Jennifer Taylor",
    category: "Classic",
    status: false,
    bookName: "The Great Gatsby",
  },
  {
    author: "Isaac Asimov",
    owner: "William Harris",
    category: "Science Fiction",
    status: true,
    bookName: "Foundation",
  },
  {
    author: "Margaret Atwood",
    owner: "Elizabeth Clark",
    category: "Dystopian",
    status: false,
    bookName: "The Handmaid's Tale",
  },
  {
    author: "J.R.R. Tolkien",
    owner: "Christopher Lewis",
    category: "Fantasy",
    status: true,
    bookName: "The Hobbit",
  },
  {
    author: "Arthur Conan Doyle",
    owner: "Patricia Walker",
    category: "Mystery",
    status: false,
    bookName: "The Hound of the Baskervilles",
  },
];
